/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package aplikasikasir;

/**
 *
 * @author User
 */
public class OptionMenu extends javax.swing.JInternalFrame {

    /**
     * Creates new form OptionMenu
     */
    public OptionMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ToPaymentButton = new javax.swing.JButton();
        ShowDataButton = new javax.swing.JButton();

        setTitle("OPTION MENU");

        ToPaymentButton.setText("Penjualan Rumah");
        ToPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToPaymentButtonActionPerformed(evt);
            }
        });

        ShowDataButton.setText("Tampilkan Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(ToPaymentButton)
                .addGap(62, 62, 62)
                .addComponent(ShowDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowDataButton)
                    .addComponent(ToPaymentButton))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ToPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToPaymentButtonActionPerformed
        // TODO add your handling code here:
        PaymenForm PaymenForm = new PaymenForm();
        PaymenForm.setVisible(true);
        this.getDesktopPane().add(PaymenForm);
        this.dispose();
        
    }//GEN-LAST:event_ToPaymentButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ShowDataButton;
    private javax.swing.JButton ToPaymentButton;
    // End of variables declaration//GEN-END:variables
}
