/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package aplikasikasir;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class PaymenForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form PaymenForm
     */
    public PaymenForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioButton = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        OrderNametxt = new javax.swing.JTextField();
        PriceLandtxt = new javax.swing.JTextField();
        AreaComboBoxtxt = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        T36RadioButton = new javax.swing.JRadioButton();
        T45RadioButton = new javax.swing.JRadioButton();
        T54RadioButton = new javax.swing.JRadioButton();
        BuildingPricetxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        LargeLandtxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        AvailabeLandtxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ProcesButtontxt = new javax.swing.JButton();
        SaveButtontxt = new javax.swing.JButton();
        DeleteButtontxt = new javax.swing.JButton();
        TotalPricetxt = new javax.swing.JTextField();
        DPtxt = new javax.swing.JTextField();
        InstallMentAmounttxt = new javax.swing.JTextField();
        Ppntxt = new javax.swing.JTextField();
        InstallMentMonthtxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        AgreementCbxtxt = new javax.swing.JCheckBox();

        setTitle("FORM PENJUALAN ");

        jLabel1.setText("Nama Pemesan");

        jLabel2.setText("Harga Tanah");

        jLabel3.setText("Area");

        PriceLandtxt.setEditable(false);

        AreaComboBoxtxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Pilih ---", "BUGENVILE", "MELATI ", "FLANBOYAN", " ", " " }));
        AreaComboBoxtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaComboBoxtxtActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasikasir/download.jpeg"))); // NOI18N

        jLabel5.setText("Harga Bangunan");

        jLabel6.setText("Tipe Rumah");

        RadioButton.add(T36RadioButton);
        T36RadioButton.setText("Tipe-36");
        T36RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T36RadioButtonActionPerformed(evt);
            }
        });

        RadioButton.add(T45RadioButton);
        T45RadioButton.setText("Tipe-45");
        T45RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T45RadioButtonActionPerformed(evt);
            }
        });

        RadioButton.add(T54RadioButton);
        T54RadioButton.setText("Tipe-54");
        T54RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T54RadioButtonActionPerformed(evt);
            }
        });

        BuildingPricetxt.setEditable(false);

        jLabel7.setText("Luas Tanah Asli");

        LargeLandtxt.setEditable(false);

        jLabel8.setText("Luas Tanah Tersedia");

        AvailabeLandtxt.setEditable(false);

        jLabel9.setText("Harga");

        jLabel10.setText("DP");

        jLabel11.setText("Lama Cicilan");

        jLabel12.setText("PPN (10%)");

        jLabel13.setText("Cicilan/Bulan");

        ProcesButtontxt.setText("PROSES");
        ProcesButtontxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcesButtontxtActionPerformed(evt);
            }
        });

        SaveButtontxt.setText("SIMPAN");

        DeleteButtontxt.setText("HAPUS");
        DeleteButtontxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtontxtActionPerformed(evt);
            }
        });

        TotalPricetxt.setEditable(false);

        jLabel14.setText("Bulan");

        AgreementCbxtxt.setText("Setuju");
        AgreementCbxtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgreementCbxtxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(ProcesButtontxt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OrderNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PriceLandtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AreaComboBoxtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(T36RadioButton)
                            .addComponent(T45RadioButton)
                            .addComponent(T54RadioButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(BuildingPricetxt)
                            .addComponent(AvailabeLandtxt)
                            .addComponent(LargeLandtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(TotalPricetxt)
                            .addComponent(DPtxt)
                            .addComponent(InstallMentAmounttxt)
                            .addComponent(Ppntxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(SaveButtontxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DeleteButtontxt)
                            .addComponent(InstallMentMonthtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(AgreementCbxtxt))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(BuildingPricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(T36RadioButton)
                                    .addComponent(LargeLandtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(OrderNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(PriceLandtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(T45RadioButton)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3)
                            .addComponent(AreaComboBoxtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T54RadioButton)
                    .addComponent(AvailabeLandtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TotalPricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DPtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InstallMentAmounttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ppntxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(InstallMentMonthtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AgreementCbxtxt))))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProcesButtontxt)
                    .addComponent(SaveButtontxt)
                    .addComponent(DeleteButtontxt))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AreaComboBoxtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaComboBoxtxtActionPerformed
        // TODO add your handling code here:
        switch(AreaComboBoxtxt.getSelectedIndex()){
            case 0:
                PriceLandtxt.setText("");
                BuildingPricetxt.setText("");
                RadioButton.clearSelection();
                LargeLandtxt.setText("");
                AvailabeLandtxt.setText("");
                TotalPricetxt.setText("");
                DPtxt.setText("");
                InstallMentAmounttxt.setText("");
                InstallMentMonthtxt.setText("");
                Ppntxt.setText("");
                AgreementCbxtxt.setSelected(false);
            break;
            
            case 1:
                PriceLandtxt.setText("500000");
                BuildingPricetxt.setText("9000000");
                RadioButton.clearSelection();
                LargeLandtxt.setText("");
                AvailabeLandtxt.setText("");
                TotalPricetxt.setText("");
                DPtxt.setText("");
                InstallMentAmounttxt.setText("");
                InstallMentMonthtxt.setText("");
                Ppntxt.setText("");
                AgreementCbxtxt.setSelected(false);
                break;
                
            case 2:
                PriceLandtxt.setText("600000");
                BuildingPricetxt.setText("120000000");
                RadioButton.clearSelection();
                LargeLandtxt.setText("");
                AvailabeLandtxt.setText("");
                TotalPricetxt.setText("");
                DPtxt.setText("");
                InstallMentAmounttxt.setText("");
                InstallMentMonthtxt.setText("");
                Ppntxt.setText("");
                AgreementCbxtxt.setSelected(false);
                break;
                
            default :
                PriceLandtxt.setText("700000");
                BuildingPricetxt.setText("120000000");
                RadioButton.clearSelection();
                LargeLandtxt.setText("");
                AvailabeLandtxt.setText("");
                TotalPricetxt.setText("");
                DPtxt.setText("");
                InstallMentAmounttxt.setText("");
                InstallMentMonthtxt.setText("");
                Ppntxt.setText("");
                AgreementCbxtxt.setSelected(false);
                break;
        }
    }//GEN-LAST:event_AreaComboBoxtxtActionPerformed

    private void T36RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T36RadioButtonActionPerformed
        // TODO add your handling code here:
        if(AreaComboBoxtxt.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Pilih Area Terlebih Dahulu");
            RadioButton.clearSelection();
        }else {
            LargeLandtxt.setText("90");
            AvailabeLandtxt.setText("54");
            long LandPrice = Long.parseLong(PriceLandtxt.getText()),
                    BuildingPrice = Long.parseLong(BuildingPricetxt.getText()),
                    availableLand = Long.parseLong(AvailabeLandtxt.getText()),
                    TotalPrice;
            TotalPrice = (availableLand * LandPrice) + BuildingPrice;
            TotalPricetxt.setText("" + TotalPrice);
            
            InstallMentAmounttxt.setText("");
            DPtxt.setText("");
            Ppntxt.setText("");
            InstallMentMonthtxt.setText("");
        }
    }//GEN-LAST:event_T36RadioButtonActionPerformed

    private void T45RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T45RadioButtonActionPerformed
        // TODO add your handling code here:
       if(AreaComboBoxtxt.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Pilih Area Terlebih Dahulu");
            RadioButton.clearSelection();
        }else {
            LargeLandtxt.setText("120");
            AvailabeLandtxt.setText("75");
            long LandPrice = Long.parseLong(PriceLandtxt.getText()),
                    BuildingPrice = Long.parseLong(BuildingPricetxt.getText()),
                    availableLand = Long.parseLong(AvailabeLandtxt.getText()),
                    TotalPrice;
            TotalPrice = (availableLand * LandPrice) + BuildingPrice;
            TotalPricetxt.setText("" + TotalPrice);
            
            InstallMentAmounttxt.setText("");
            DPtxt.setText("");
            Ppntxt.setText("");
            InstallMentMonthtxt.setText("");
       }
    }//GEN-LAST:event_T45RadioButtonActionPerformed

    private void T54RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T54RadioButtonActionPerformed
        // TODO add your handling code here:
       if(AreaComboBoxtxt.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Pilih Area Terlebih Dahulu");
            RadioButton.clearSelection();
        }else {
            LargeLandtxt.setText("140");
            AvailabeLandtxt.setText("86");
            long LandPrice = Long.parseLong(PriceLandtxt.getText()),
                    BuildingPrice = Long.parseLong(BuildingPricetxt.getText()),
                    availableLand = Long.parseLong(AvailabeLandtxt.getText()),
                    TotalPrice;
            TotalPrice = (availableLand * LandPrice) + BuildingPrice;
            TotalPricetxt.setText("" + TotalPrice);
            
            InstallMentAmounttxt.setText("");
            DPtxt.setText("");
            Ppntxt.setText("");
            InstallMentMonthtxt.setText("");
       }
    }//GEN-LAST:event_T54RadioButtonActionPerformed

    private void DeleteButtontxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtontxtActionPerformed
        // TODO add your handling code here:
        OrderNametxt.setText("");
        PriceLandtxt.setText("");
        BuildingPricetxt.setText("");
        LargeLandtxt.setText("");
        AvailabeLandtxt.setText("");
        TotalPricetxt.setText("");
        DPtxt.setText("");
        InstallMentAmounttxt.setText("");
        InstallMentMonthtxt.setText("");
        Ppntxt.setText("");
        AreaComboBoxtxt.setSelectedIndex(0);
        RadioButton.clearSelection();
        AgreementCbxtxt.setSelected(false);
       
    }//GEN-LAST:event_DeleteButtontxtActionPerformed

    private void ProcesButtontxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcesButtontxtActionPerformed
        // TODO add your handling code here:
        if(TotalPricetxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilihan Belum Lengkap");
        }else if(DPtxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "DP Harus Diisi");   
        }else if(InstallMentAmounttxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Isi Jumlah Cicilan Yang Diinginkan");
        }else {
            long LandPrice = Long.parseLong(PriceLandtxt.getText()),
                    BuildingPrice = Long.parseLong(BuildingPricetxt.getText()),
                    availableLand = Long.parseLong(AvailabeLandtxt.getText()),
                    dp = Long.parseLong(DPtxt.getText()),
                    instalmentAmount = Long.parseLong(InstallMentAmounttxt.getText()),
                    TotalPrice, Ppn, instalmentPerMouth;
            TotalPrice = (availableLand * LandPrice) + BuildingPrice;
            Ppn = TotalPrice * 10 / 100;
            instalmentPerMouth = (TotalPrice + Ppn) / instalmentAmount;
            Ppntxt.setText("" + Ppn);
            InstallMentMonthtxt.setText("" + instalmentPerMouth);
    }//GEN-LAST:event_ProcesButtontxtActionPerformed
    }
    private void AgreementCbxtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgreementCbxtxtActionPerformed
        // TODO add your handling code here:
        if(OrderNametxt.getText(). isEmpty()){
            JOptionPane.showMessageDialog(null, "Name Pemesan Harus Diisi");
            AgreementCbxtxt.setSelected(false);
        }else if(Ppntxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Tekan Tombol Proses Terlebih Dahulu");
            AgreementCbxtxt.setSelected(false);
        }else if(AgreementCbxtxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pemesan Menyetujui");
            AgreementCbxtxt.setSelected(true);
        }else {
            JOptionPane.showMessageDialog(null, "Pemesan Belum Menyetujui");
            AgreementCbxtxt.setSelected(false);
    }//GEN-LAST:event_AgreementCbxtxtActionPerformed

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AgreementCbxtxt;
    private javax.swing.JComboBox<String> AreaComboBoxtxt;
    private javax.swing.JTextField AvailabeLandtxt;
    private javax.swing.JTextField BuildingPricetxt;
    private javax.swing.JTextField DPtxt;
    private javax.swing.JButton DeleteButtontxt;
    private javax.swing.JTextField InstallMentAmounttxt;
    private javax.swing.JTextField InstallMentMonthtxt;
    private javax.swing.JTextField LargeLandtxt;
    private javax.swing.JTextField OrderNametxt;
    private javax.swing.JTextField Ppntxt;
    private javax.swing.JTextField PriceLandtxt;
    private javax.swing.JButton ProcesButtontxt;
    private javax.swing.ButtonGroup RadioButton;
    private javax.swing.JButton SaveButtontxt;
    private javax.swing.JRadioButton T36RadioButton;
    private javax.swing.JRadioButton T45RadioButton;
    private javax.swing.JRadioButton T54RadioButton;
    private javax.swing.JTextField TotalPricetxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
